name: "Construção e Execução do Docker Compose"

on:
  push:
    branches: [ "main", "dev/renan" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
