name: "Construção e Execução do Docker Compose"

on:
  push:
    branches: [ "main", "dev/renan" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Docker to the latest version
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          docker --version

      - name: Build the stack
        run: docker compose up -d

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: renancesu
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Save Docker Compose logs
        run: docker compose logs > docker-compose-logs.txt

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp docker-compose.yml artifacts/
          cp docker-compose-logs.txt artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-artifacts
          path: artifacts/
