name: node-pre-push
on:
  push:
    branches:
      - main
      - "*"
    paths:
      - "magic-api/**"
jobs:
  test:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
      - name: Instala as dependencias
        run: npm i
        working-directory: magic-api
      - name: Roda o linter
        run: npm run lint
        working-directory: magic-api
